# Generated by Django 5.0.4 on 2024-04-03 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('partmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='builder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builder', to='home.member'),
        ),
    ]
