# Generated by Django 5.0.4 on 2024-04-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partmanager', '0002_alter_part_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='endtime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='finished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='starttime',
            field=models.DateField(null=True),
        ),
    ]
