# Generated by Django 5.0.4 on 2024-04-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partmanager', '0003_part_endtime_part_finished_part_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='started',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
