# Generated by Django 5.0.4 on 2024-04-07 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('partmanager', '0005_part_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='builder',
        ),
        migrations.RemoveField(
            model_name='part',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='part',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='part',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='part',
            name='started',
        ),
        migrations.RemoveField(
            model_name='part',
            name='starttime',
        ),
        migrations.AddField(
            model_name='part',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='designer', to='home.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Electrical Review'), (2, 'Mentor Aproval'), (3, 'Official Release'), (4, 'Manufacturing'), (5, 'Quality Control'), (6, 'Assembly'), (7, 'Done')], default=1),
        ),
    ]
